# Site settings
title: "Jonathan's Blog"
description: "My stuff"
baseurl: ""
url: "http://alixedi.github.io"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
# paginate: 3

# Links
links:
  - title: "abt"
    url: /about
  - title: "twt"
    url: http://twitter.com/jdayton23
  - title: "git"
    url: http://github.com/jdayton3
  - title: "rss"
    url: /feed.xml

# Gems
gems: [jekyll-paginate]
paginate: 3
paginate_path: "page:num"
